### ISSUE TITLE
Dumps of other image sizes

### ISSUE THREAD

**Issue by misiek08** [atc1441/ATC_GICISKY_ESL#1]
Hello!
Quick story: I got few 2.13" labels, but the app I got with them is very bad and also uploading any custom style requires using chinese web portal hosted on IP, single server.

Question: how did you get binary data of the image? Is it possible to get some more for different sizes, especially pixel count? I tried to look into this bad application source code, but it is a little bit obfuscated and made in Flutter so it will take some time to decode protocol.

**Comment by atc1441** [comment]
Hey, try out the newest version of the Uploader linked in the repo please

**Comment by misiek08** [comment]
Had no time last few weeks to look here, but now I've checked the progress. You are a goat! Thanks for this example!
